### ISSUE TITLE
Bot won't start

### ISSUE THREAD

**Issue by TheFrodo** [sGfU/discord-teamspeak-statusbot#1]
Hey, 
First of all, sorry for my bad English.
I'm writing to you regarding the discord-teamspeak-statusbot on github. I just installed it, but it gives me the following error: 

`root/tsstatus/bot.js:13
        return client.user.setActivity(`${players}/${maxplayers} on Teamspeak!`);
                           ^

TypeError: Cannot read property 'setActivity' of null
    at Request.request.get [as _callback] (/root/tsstatus/bot.js:13:28)
    at Request.self.callback (/root/tsstatus/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/root/tsstatus/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/root/tsstatus/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Bot stopped with exit code 1. Restarting...
Successfully updated the status of your Teamspeak!
/root/tsstatus/bot.js:13
        return client.user.setActivity(`${players}/${maxplayers} on Teamspeak!`);
`

Do you think you could possibly help me with this?

**Comment by sGfU** [comment]
I’ll take a look when I’m home, see if it still works on my end and see if I can diagnose your issue.
